### ISSUE TITLE
Support for TYPO3 Neos 1.2.1

### ISSUE THREAD

**Issue by kpostrup** [lelesys/Lelesys.Plugin.IndexedSearch#2]
It would be nice if we could have support for the latest TYPO3 Neos 1.2.1. Current version is incompatible with Neos 1.2.1 when installing through composer.phar.

**Comment by desaisagar** [comment]
Hey Kenneth Østrup,

I have created new branch 1.2 for 1.2.1 fixes. The plugin is working with 1.2.1 but not yet fully tested at the moment. Please report if you get any issues.

Use composer require "lelesys/plugin-indexed-search:1.2.x-dev" command for installation.

Thanks!!!
Sagar Desai
http://www.lelesys.com

**Comment by kpostrup** [comment]
@desaisagar,
It installs perfectly through composer now. Everything seems to be in order. Thank you very much.
